server:
  port: 8040

spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-data/**
      serviceId: data-service
    api-b:
      path: /api-view/**
      serviceId: view-service