# redis??
spring:
  application:
    name: util-service
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0
    lettuce:
      pool:
        max-active: 8
        min-idle: 8
        max-wait: -1
        max-idle: 8
        shutdown-timeout: 100

cache:
  ehcache:
     config: ehcache.xml

logging:
  level:
    com.example.battle: debug
  pattern:
    console: %d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n
