# redis??
spring:
  application:
    name: util-service
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0

cache:
  ehcache:
     config: ehcache.xml
